#
# Copyright The OpenZipkin Authors
# SPDX-License-Identifier: Apache-2.0
#

# This file uses the version 2 docker compose file format, described here:
# https://docs.docker.com/compose/compose-file/#version-2
#
# It extends the default configuration from docker-compose.yml to add a test
# pulsar server, which is used as a span transport.

version: '2.4'

services:
  pulsar:
    image: ghcr.io/openzipkin/zipkin-pulsar:${TAG:-latest}
    container_name: pulsar
    ports: # expose the pulsar port so apps can publish spans.
      - "6650:6650"
      # - "8080:8080" # uncomment to expose the pulsar http port.

  zipkin:
    extends:
      file: docker-compose.yml
      service: zipkin
    # slim doesn't include Pulsar support, so switch to the larger image
    image: ghcr.io/openzipkin/zipkin:${TAG:-latest}
    environment:
      - PULSAR_SERVICE_URL=pulsar://pulsar:6650
    depends_on:
      pulsar:
        condition: service_healthy
